### ISSUE TITLE
Small suggestion: use tinytest instead of testthat, to be more in line with fastverse principles

### ISSUE THREAD

**Issue by tony-aw** [SebKrantz/collapse#443]
Hi,

Small suggestion:
To make the `collapse` R package more in line with fastverse (and tinyverse) principles, you might want to perhaps run your tests using the `tinytest` R package, instead of `testthat`. This is just a small suggestion though, nothing more.

Kind regards,

Tony

**Comment by SebKrantz** [comment]
Thanks, I agree it's a huge bloat to install on a server. I'll look into it as I find time. I like the integration of `testthat` with Rstudio, that's why I have kept it, and it doesn't really matter for CRAN as those servers have all packages preinstalled. 

You can omit installing suggested packages by adding `dependencies = "NA"` to your YAML: 

```yaml

jobs:
  MyJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: "r"
          cache-version: 2
          dependencies: "NA"
```
